---
### Variables listed here are applicable to all host groups

######################################################
### Plesk settings begin

### Define URL for license file
# plesk_license_url: "<TBD_license_file_URL>"

### Activation code for trial license can be obtained here http://www.plesk.com/download
plesk_license_activation_code: A00J00-NBNH04-M5YD13-9K9733-YPCA99

### Installation parameters
one_click_installer: https://autoinstall.plesk.com/one-click-installer
plesk_installer: https://autoinstall.plesk.com/plesk-installer
plesk_tier: testing

### Extensions catalog URL
extore_url: https://ext.plesk.com


### Plesk initialization parameters
eula_license_agreed: true
ip_type: shared
admin_info_not_required: true
admin_email: support@biznetgio.com
admin_company: PT Biznet Gio Nusantara
admin_address: DKI Jakarta
admin_city: Jakarta
admin_state: Indonesia
admin_zip: 630000
admin_country: ID
admin_phone: 085692091009

### Plesk settings end
######################################################




######################################################
### VM settings begin

### Swapfile size
swapsize: 1G

### SSH key private part
ssh_key_file: ~/.ssh/id_rsa
ssh_pubkey_file: ~/.ssh/id_rsa.pub

### Server settings begin
######################################################




######################################################
### Digitalocean settings begin

do_project_name: "plesk-ansible-{{ansible_date_time.epoch}}.plesk.space"

### To get a list of all DC regions
#list_of_regions='curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer 534420db28eb92a7dba3c73834cd246090de0ae2ec1d1bb45407889ec27279da" "https://api.digitalocean.com/v2/regions"'
do_region_id: fra1

### To get list of all VM sizes
#list_of_sizes='curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer 534420db28eb92a7dba3c73834cd246090de0ae2ec1d1bb45407889ec27279da" "https://api.digitalocean.com/v2/sizes"'
do_size_id: 512mb

### to get a list of available SSH keys 
# curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer 534420db28eb92a7dba3c73834cd246090de0ae2ec1d1bb45407889ec27279da" "https://api.digitalocean.com/v2/account/keys"
do_ssh_key_id: 2009036

### OS image
# curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer 534420db28eb92a7dba3c73834cd246090de0ae2ec1d1bb45407889ec27279da" "https://api.digitalocean.com/v2/images"
do_image_id: centos-7-2-x64

### Digitalocean settings end
######################################################




