---

- set_fact:
    ssh_delay: 60
  when: ssh_delay is undefined

- set_fact:
    ssh_timeout: 400
  when: ssh_timout is undefined

- name: Wait for SSH to come up
  wait_for:
    host: "{{item}}"
    port: 22
    delay: "{{ssh_delay}}"
    timeout: "{{ssh_timeout}}"
    state: started
  with_items: "{{hosts_to_check}}"
  when: hosts_to_check is defined

- name: Wait for SSH to come up
  wait_for:
    host: "{{host_to_check}}"
    port: 22
    delay: "{{ssh_delay}}"
    timeout: "{{ssh_timeout}}"
    state: started
  when: host_to_check is defined

- pause:
    seconds: 15