---
# This playbook contains common plays that will be run on all nodes.

- name: Create swapfile
  shell: if [ ! -f /swapfile ]; then fallocate -l {{swap_size}} /swapfile; fi
  register: result
  tags: swapfile

- file: path=/swapfile mode=600
  tags: swapfile

- name: Configure swapfile
  shell: swapon -s /swapfile | grep -i swapfile || ( mkswap /swapfile && swapon /swapfile )
  tags: swapfile

- name: Add swap partition to fstab
  shell: grep -i 'swapfile' /etc/fstab || echo '/swapfile   none    swap    sw    0   0' >> /etc/fstab
  tags: swapfile
